spring.application.name=Taxol760
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taxol760}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:taxol760}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:taxol760}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false
