### Register user
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "email": "user@taxol.test",
  "name": "Taxol User",
  "password": "password123",
  "phoneNumber": "5550001111",
  "role": "USER"
}

### Login user
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "user@taxol.test",
  "password": "password123"
}
