@driverId = 10
@driverUserId = 1
@licenseNumber = LIC-10

### Create driver
POST {{host}}/api/drivers
Content-Type: application/json

{
  "userId": {{driverUserId}},
  "licenseNumber": "{{licenseNumber}}"
}
