@rideId = 30
@riderId = 1
@rideDriverId = 10
@rideStatus = REQUESTED

### Request ride
POST {{host}}/api/rides
Content-Type: application/json

{
  "riderId": {{riderId}},
  "pickupLatitude": 41.7151,
  "pickupLongitude": 44.8271,
  "dropoffLatitude": 41.7251,
  "dropoffLongitude": 44.8371
}

### Get all rides
GET {{host}}/api/rides

### Get ride by id
GET {{host}}/api/rides/{{rideId}}

### Get rides by status
GET {{host}}/api/rides/status/{{rideStatus}}

### Get rides by rider id
GET {{host}}/api/rides/rider/{{riderId}}

### Get rides by driver id
GET {{host}}/api/rides/driver/{{rideDriverId}}

### Accept ride
POST {{host}}/api/rides/{{rideId}}/accept?driverId={{rideDriverId}}

### Start ride
POST {{host}}/api/rides/{{rideId}}/start

### Complete ride
POST {{host}}/api/rides/{{rideId}}/complete

### Cancel ride
POST {{host}}/api/rides/{{rideId}}/cancel
