@vehicleId = 20
@vehicleDriverId = 10
@plateNumber = TAX-20

### Create vehicle
POST {{host}}/api/vehicles
Content-Type: application/json

{
  "driverId": {{vehicleDriverId}},
  "brand": "Toyota",
  "model": "Prius",
  "color": "White",
  "plateNumber": "{{plateNumber}}"
}

### Get all vehicles
GET {{host}}/api/vehicles

### Get vehicle by id
GET {{host}}/api/vehicles/{{vehicleId}}

### Get vehicle by driver id
GET {{host}}/api/vehicles/driver/{{vehicleDriverId}}

### Get vehicle by plate number
GET {{host}}/api/vehicles/plate/{{plateNumber}}
