@vehicleId = 20
@vehicleDriverId = 10
@plateNumber = TAX-20

### Create vehicle
POST {{host}}/api/vehicles
Content-Type: application/json

{
  "driverId": {{vehicleDriverId}},
  "brand": "Toyota",
  "model": "Prius",
  "color": "White",
  "plateNumber": "{{plateNumber}}"
}
